#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# restore wallpaper
xsetroot -solid '#000000'
~/.fehbg &

###################################
# THEME
###################################
hc set frame_border_active_color '#757575'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color 'transparent'
hc set frame_bg_active_color 'transparent'
hc set frame_border_width 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 3
hc set frame_gap 4
hc set smart_frame_surroundings 'hide_all'
hc set smart_window_surroundings 0

hc attr theme.active.color '#adadad'
hc attr theme.normal.color '#212121'
hc attr theme.urgent.color '#ffffff'
hc attr theme.inner_width 0
hc attr theme.inner_color '#000000'
hc attr theme.border_width 3
hc attr theme.floating.border_width 3
hc attr theme.floating.outer_width 3
hc attr theme.floating.outer_color '#212121'
hc attr theme.active.inner_color '#bdbdbd'
hc attr theme.active.outer_color '#adadad'
hc attr theme.background_color '#121212'

hc set show_frame_decorations 'none'
hc set window_gap 10
hc set frame_padding 0
hc set default_frame_layout 'grid'

###################################
# KEYBINDS
###################################
# remove all existing keybindings
hc keyunbind --all

#Mod=Mod1   # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-w spawn firefox
hc keybind $Mod-Shift-s spawn flameshot gui
hc keybind $Mod-y spawn dmenu_run -b -i -fn "fixed-18"
hc keybind $Mod-Return spawn "${TERMINAL:-xterm}"

#hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep


###################################
# TAGS
###################################
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

###################################
# RULES
###################################
hc unrule -F
hc rule focus=on
# hc rule floatplacement=smart
hc rule floatplacement=center
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

# InputLeap and pavucontrol goes floating
hc rule class~'pavucontrol' floating=on
hc rule class~'InputLeap' floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

###################################
# MONITORS & PANELS
###################################
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
hc detect_monitors

# start a panel on each monitor
panel=~/.config/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    "$panel" "$monitor" &
done


###################################
# AUTOSTART APPS
###################################
if hc silent new_attr bool my_not_first_autostart ; then
    "$HOME/projects/utils/exec_on_tag.sh" 1 wezterm &
    "$HOME/projects/utils/exec_on_tag.sh" 2 firefox &
    "$HOME/projects/utils/exec_on_tag.sh" 3 thunderbird &
    "$HOME/projects/utils/exec_on_tag.sh" 3 "$HOME/projects/utils/whatsappweb.sh" &
    "$HOME/projects/utils/exec_on_tag.sh" 8 "$HOME/projects/utils/camera.sh" &
    "$HOME/projects/utils/exec_on_tag.sh" 9 input-leap &
    hc chain , focus_monitor 1 , use_index 7 , focus_monitor 0 , use_index 0
fi
